# fifo example

TOPLEVEL_LANG = verilog
SIM = icarus
VERILOG_SOURCES = hdl/axis_fifo.v hdl/fifo_fwft.v hdl/mem.v
MODULE = test_axis_fifo
TOPLEVEL = axis_fifo

include $(shell cocotb-config --makefiles)/Makefile.sim